name: Deploy Firebase Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm install -g firebase-tools
      - run: cd functions && npm install
      - run: firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}" --project sa-enxovais
