name: Deploy Firebase Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm install -g firebase-tools
      - run: cd functions && npm install
      - run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > /tmp/sa.json
      - run: firebase deploy --only functions --project sa-enxovais
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/sa.json
          MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}
